spring.application.name=Data-Migration

# Add retryWrites=false to the connection string
spring.data.mongodb.uri=mongodb://localhost:27017/mongo-migration?retryWrites=false

# OR keep your existing config and add this:
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mongo-migration

mongock.migration-scan-package=com.mongo.Data.Migration
mongock.throw-exception-if-cannot-obtain-lock=false
mongock.track-ignored=false
mongock.enabled=true
mongock.transaction-enabled=false